filename: cpap.csv # CSV file
seed: 42
min_pressure: 7 # min pressure
max_pressure: # max pressure
max_leak_rate: 1.2 # max AvgLR
min_usage: 6 # min usage (hrs)
num_correlations: 10 # num correlations to display
alpha: 0.02 # alpha for ElasticNet regression
l1_ratio: 0.8 # l1_ratio for ElasticNet regression
plot: true # true to enable plotting
plot_quadratic: true # include quadratic regression in plots
save_plots: false # save plots to {column}.png
weighted: true # true to use Inverse Probability Weighting
y_fields: # fields to calculate with optional title for plotting and plot flag to allow plotting if globally enabled
  - name: Comb FL
    title: Combined FL (WAT/NED)
    plot: true
  - name: FLS
    title: Flow Limitation Score (WAT)
    plot: true
  - name: GI
    title: Glasgow Index
    plot: true
  - name: NED RDI
    title: Est. RDI (NED)
    plot: true
  - name: BOI
    title: Brief Obstruction Index
    plot: true
  - name: Usage
    title: Usage (AS11)
    enabled: false
  - name: AHI
    title: AHI (AS11)
  - name: CAI
    title: CAI (AS11)
  - name: RDI
    title: RDI (AS11)
  - name: 95%FL
    title: 95% Flow Limitation (AS11)
  - name: AvgLR
    title: Average Leak Rate (AS11)
  - name: IFL
    title: IFL Symptom Risk % (WAT/NED/GI)
  - name: NED Mean
    title: NED Mean (NED)
  - name: NED RERA
    title: RERA/hr (NED)
  - name: GI TH
    title: 'Glasgow Index: Top-Heavy'
    enabled: false
  - name: GI VA
    title: 'Glasgow Index: Variable Amplitude'
    enabled: false
  - name: Period
    title: Periodicity (WAT)
  - name: Regul
    title: Regularity (WAT)
  - name: RHR
    title: Resting Heart Rate (Oura)
    enabled: false
  - name: HRV
    title: Heart Rate Variability (Oura)
    enabled: false
  - name: SpO2
    title: SpO2 (Oura)
    enabled: false