data_file: cpap.csv # CSV file
tag: # optional tag for saved files
save_logs: false # save logs (unless stats are disabled)
stats:
  enabled: true # false to disable all stats and log file
  bucket: false # true to combine adjacent pressures (works best with even number of pressures, can also use pressure_transform)
filter:
  max_days: 56 # optional maximum number of days to include (applied after min_date and max_date)
  min_date:  # optional min date in yyyy-mm-dd format
  max_date:  # optional max date in yyyy-mm-dd format
  min_pressure:  # optional min Pressure
  max_pressure:  # optional max Pressure
  max_leak_rate: 1.5 # optional max AvgLR
  min_usage: 6.0 # optional min Usage (hrs)
  min_sleep: 5.5 # optional min Sleep (hrs)
  min_sleep_efficiency: 0.75 # optional min ratio between Sleep and Usage
  collar: 0 # optional collar value (0 for no collar, 1 for collar, or null for both)
  verbose: false # print details for configuration-based filtering
pressure_transform: # use to combine pressure with another pressure (applied before filters)
  6.8: 7.0 # combine single 6.8 row with 7.0
  8.2: 8.0 # combine single 8.2 row with 8.0
pressure_counts:
  enabled: true # true to show a breakdown of dates for each pressure
  max_dates: 5 # optional maximum number of dates displayed for each pressure
  pressure_date_correlation: true # true to display pressure/date correlation
next_pressure:
  enabled: true # true to enable recommending next pressure (choose lowest adjusted pressure count)
  last_pressure_boost: 3 # optional boost for last pressure (positive number reduces adjusted count)
  random_sigma: 0.5 # optional sigma used to randomly adjust counts (low value for tie-breaker, larger value for more randomization)
  pressure_boosts: # dictionary of pressure boosts (positive number reduces adjusted count)
  center_weight: 0 # multiplier applied to distance from pressure that will center mean
  verbose: true
weighted_by:
  frequency: false # true to weight by inverse frequency for pressure
  usage: false # true to weight by usage
all_correlations:
  enabled: false # true to run correlations between all enabled fields
  num_correlations: # optional number of correlations to display between all fields (null to display all)
  min_correlation: 0.5 # optional minimum correlation to display (default 0)
correlation:
  enabled: false # true to enable linear regression (including correlation and plotting)
  num_correlations:  # optional number of correlations to display for field in x_fields (null to display all)
  min_correlation: 0.2 # optional minimum correlation to display (default 0)
r2:
  linear: true # true to display linear R² scores
  quadratic: true # true to display quadratic R² scores
  num_scores: 5 # optional number of r2 scores to display for field in x_fields (null to display all)
  min_score:  # optional minimum correlation to display (default 0)
plot:
  enabled: true # true to enable plotting when enabled for both x and y fields
  violin: false # true for violin plot
  box: true # true for box plot
  linear: false # true to plot scatter plot and linear regression
  quadratic: false # include plot scatter plot and quadratic regression (combined with linear if both are true)
  save: false # save plots
elastic_net:
  enabled: false # true to enable ElasticNet regression using multi_x_field
  alpha: 1.0 # alpha for ElasticNet regression
  l1_ratio: 1.0 # l1_ratio for ElasticNet regression
  seed: 42 # random seed
bayesian_ridge:
  enabled: false # perform BayesianRidge regression using multi_x_field
  min_weight: 0.2 # optional minimum BayesianRidge weight to print (default 0)
ard:
  enabled: false # perform ARD Bayesian regression using multi_x_field
  min_weight: 0.2 # optional minimum ARD weight to print (default 0)
# fields
# - key: key in CSV
# - name: optional display name (defaults to key)
# - title: optional title for plotting (defaults to name)
# - plot: true to enable linear/quadratic plotting (must be true for both fields and globally enabled)
# - y_field: true if used as a y field (will also be used for regularization unless multi_x_field is true)
# - x_field: true if used as an x field for correlation and linear regression
# - multi_x_field: true if used as an x field for regularization (e.g. ElasticNet)
fields:
  - key: Comb FL
    name: Combined FL
    y_field: true
    plot: true
  - key: FLS
    name: Flow Limitation Score
    y_field: true
  - key: GI
    name: Glasgow Index
    y_field: true
    plot: true
  - key: GI Sk
    name: GI Skew
    y_field: true
  - key: GI Sp
    name: GI Spike
    y_field: true
  - key: GI FT
    name: GI Flat Top
    y_field: true
  - key: GI TH
    name: GI Top Heavy
    y_field: true
  - key: GI MP
    name: GI Multi Peak
    y_field: true
  - key: GI NP
    name: GI No Pause
    y_field: true
  - key: GI IR
    name: GI Inspiration Rate
    y_field: true
  - key: GI MB
    name: GI Multi Breath
    y_field: true
  - key: GI VA
    name: GI Var Amp
    y_field: true
  - key: NED Mean
    y_field: true
  - key: H1 NED Mean
    y_field: false
  - key: H2 NED Mean
    y_field: false
  - key: NED Mean Split # calculated: abs(H2 NED Mean - H1 NED Mean)
    y_field: false
  - key: NED RDI
    y_field: true
    plot: true
  - key: BOI
    name: Brief Obstruction Index
    y_field: true
    plot: true
  - key: AHI
    y_field: true
  - key: RERA
    y_field: true
  - key: RDI # calculated: AHI + RERA
    y_field: true
  - key: CAI
    y_field: true
    plot: true
  - key: 95%FL
    name: 95% Flow Limitation
  - key: AvgLR
    name: Average Leak Rate
    x_field: false
    y_field: true
    multi_x_field: true
  - key: IFL
    title: IFL Symptom Risk %
    y_field: true
  - key: Period
    name: Periodicity
    y_field: true
  - key: Regul
    name: Regularity
    y_field: true
  - key: Timestamp # numeric Date
    name: Date
    x_field: false
    multi_x_field: true
  - key: Pressure
    plot: true
    x_field: true
    multi_x_field: true
  - key: Collar
    plot: false
    x_field: false # TODO experiment with collar (disable other x fields)
    multi_x_field: true # TODO experiment with collar
  - key: Usage
  - key: Sleep
  - key: REM
  - key: Deep
  - key: Efficiency # Calculated: Usage / Sleep
    name: Sleep Efficiency


