filename: cpap.csv # CSV file
seed: 42
min_pressure: 7.0 # min Pressure
max_pressure: # max Pressure
max_leak_rate: 1.6 # max AvgLR
min_usage: 6.0 # min Usage (hrs)
min_sleep: 5.5 # min Sleep (hrs)
min_sleep_efficiency: 0.75 # min ratio between Sleep and Usage
num_correlations: 5 # num correlations to display (0 for all)
alpha: 0.05 # alpha for inverse ElasticNet regression (null to disable)
l1_ratio: 1.0 # l1_ratio for ElasticNet regression
bayesian: false # perform an inverse Bayesian ridge regression
plot: true # true to enable plotting
plot_quadratic: false # include quadratic regression in plots
save_plots: false # save plots to {column}.png
weight_frequency: false # true to weight by inverse frequency for pressure
weight_usage: false # true to weight by usage
y_fields: # fields to calculate with optional title for plotting and plot flag to allow plotting if globally enabled
  - name: Comb FL
    title: Combined FL (WAT/NED)
    plot: true
  - name: FLS
    title: Flow Limitation Score (WAT)
    plot: true
  - name: GI
    title: Glasgow Index
    plot: true
  - name: NED RDI
    title: Est. RDI (NED)
    plot: true
  - name: BOI
    title: Brief Obstruction Index
    plot: true
  - name: Usage
    title: Usage (AS11)
    enabled: false
  - name: AHI
    title: AHI (AS11)
  - name: CAI
    title: CAI (AS11)
  - name: RDI
    title: RDI (AS11)
  - name: 95%FL
    title: 95% Flow Limitation (AS11)
  - name: AvgLR
    title: Average Leak Rate (AS11)
  - name: IFL
    title: IFL Symptom Risk % (WAT/NED/GI)
  - name: NED Mean
    title: NED Mean (NED)
  - name: NED RERA
    title: RERA/hr (NED)
  - name: Period
    title: Periodicity (WAT)
  - name: Regul
    title: Regularity (WAT)
